version: '3.4'

services:
  app:
    container_name: app
    build:
      dockerfile: app/Dockerfile
    ports:
      - 5000:5000
    healthcheck:
      test: curl --fail http://localhost:5000/health-check || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - mexico-gas-price-api


networks:
  mexico-gas-price-api:
    driver: bridge

